[book]
src = "src"
title = "Engage Protocol"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
mathjax-support = true
git-repository-url = "https://github.com/Engage-Protocol/engage-protocol"

[output.html.fold]
enable = true
